### ISSUE TITLE
luet search --artifacts

### ISSUE THREAD

**Issue by nomorelogic** [geaaru/luet#26]
**Luet version:**

luet version 0.36.0-geaaru-g5b40f33fb60434eabe2f6db8ec0cfb95768b0022 2023-06-06 05:21:24 UTC - go1.20.4

**CPU architecture, OS, and Version:**

Linux mactest 6.1.31-macaroni #6.1.31-Macaroni SMP PREEMPT_DYNAMIC Fri Jun  2 09:49:44 UTC 202 x86_64 GNU/Linux

**Describe the bug**

runtime error is raised, follow details

# luet search libreoffice --artifacts
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17a213f]

goroutine 1 [running]:
github.com/geaaru/luet/cmd.newSearchCommand.func2(0xc000005800?, {0xc0002d78e0?, 0x2?, 0x2?})
	/luetbuild/luet/cmd/search.go:234 +0xaff
github.com/spf13/cobra.(*Command).execute(0xc000005800, {0xc0002d78c0, 0x2, 0x2})
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002e6300)
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/luetbuild/luet/vendor/github.com/spf13/cobra/command.go:992
github.com/geaaru/luet/cmd.Execute()
	/luetbuild/luet/cmd/root.go:186 +0x1c9
main.main()
	/luetbuild/luet/luet.go:6 +0x17

**To Reproduce**

execute a search using --artifacts flag, i.e.:
# luet search libreoffice --artifacts

**Expected behavior**

**Logs**

**Additional context**

**Comment by geaaru** [comment]
Thanks for the report.

This happens only for console output. I missing to handle correctly the Artifacts flag in that mode.
